logging:
  pattern:
    console: "%logger{1} | %msg%n"
    #console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{1.} | %msg%n"

  level:
    org.springframework: WARN
    com.ulisesbocchio.jasyptspringboot: WARN
    com.example.test: DEBUG
